name: Create Zip for Delivery

on:
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set ZIP_NAME with current date
        run: echo "ZIP_NAME=DMAV_ilivalidator_$(date +'%Y-%m-%d').zip" >> $GITHUB_ENV

      - name: Create zip file
        run: zip -r "$ZIP_NAME" ilitools repositories README.md README_fr.md README_it.md LICENSE

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Delivery
          path: ${{ env.ZIP_NAME }}
